// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAujCccRWbzSuD_bOxd9mOJMWIg_-ppEog',
    appId: '1:452097467192:web:8315c8f4b8dc29feedd7cd',
    messagingSenderId: '452097467192',
    projectId: 'eml-ev-l5',
    authDomain: 'eml-ev-l5.firebaseapp.com',
    storageBucket: 'eml-ev-l5.appspot.com',
    measurementId: 'G-W601F1VX24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTNtcHaY4RdRGqqLHk_eKV0-BpFjz6pJg',
    appId: '1:452097467192:android:ee186bf1611a9a7eedd7cd',
    messagingSenderId: '452097467192',
    projectId: 'eml-ev-l5',
    storageBucket: 'eml-ev-l5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bLABfaWFobHoVZ4yZ2BApE4_DTZlm-k',
    appId: '1:452097467192:ios:ce89f2dad7ec477bedd7cd',
    messagingSenderId: '452097467192',
    projectId: 'eml-ev-l5',
    storageBucket: 'eml-ev-l5.appspot.com',
    androidClientId: '452097467192-9tfjiq8ukh4hg32q1mms8tel77ji6uk9.apps.googleusercontent.com',
    iosClientId: '452097467192-ocr0vl5k5ijhoo1ci6rseg9ak0r374la.apps.googleusercontent.com',
    iosBundleId: 'com.santosenoque.flutterWebDashboard',
  );
}
